ollama:
  model: llama3.1:latest # you get to choose.
  endpoint: http://localhost:11434/api/chat
  system_prompt: |
    You are an assistant that rewrites notes for developer documentation.
    - Keep the meaning exactly the same.
    - Do NOT add new context.
    - Make it clear, concise, and direct.
    - Return exactly one line.
    - Do not say "Sure", "Here", or any greeting.
